[package]
name = "terraform-provider-wapc"
version = "0.1.0"
authors = ["Kit Ewbank <Kit_Ewbank@hotmail.com>"]
edition = "2018"

[dependencies]
prost = "0.6.1"

[build-dependencies]
prost-build = { version = "0.6.1" }
