[package]
name = "wapc-rust-example"
version = "1.0.0"
authors = ["Kit Ewbank <Kit_Ewbank@hotmail.com>"]
edition = "2018"
license = "Unlicense"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
wapc-guest = "0.3.1"
serde_json = "1.0.57"
